ListenAddr = "off"
MappingFile = "/etc/ktranslate/config.json"
UDRSFile = "/etc/ktranslate/udr.csv"
GeoFile = "/etc/ktranslate/GeoLite2-Country.mmdb"
ASNFile = "/etc/ktranslate/GeoListe2-ASN.mmdb"
ApplicationFile = ""
APIDevicesFile = "/etc/ktranslate/devices.json"
SNMPFile = ""
DNS = ""
ProcessingThreads = 1
InputThreads = 1
MaxThreads = 1
Format = "flat_json"
FormatRollup = ""
Compression = "none"
Sinks = "stdout"
MaxFlows = 10000
RollupInterval = 0
RollupAndAlpha = false
SampleRate = 1
SampleMin = 1
EnableSNMPDiscovery = false
KentikEmail = ""
KentikPlan = 0
APIBaseURL = "https://api.kentik.com"
SSLCertFile = ""
SSLKeyFile = ""
TagMapType = ""
VPCSource = ""
FlowSource = ""
EnableTeeLogs = false
SyslogListenAddr = ""
EnableHTTPInput = false
EnricherURL = ""
